unit TesteCargos;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, Vcl.StdCtrls, Modulo, Vcl.Buttons,
  System.SysUtils, System.Variants, Vcl.Graphics, Cargos, System.UITypes, Vcl.Grids,
  Vcl.DBGrids, Winapi.Messages, Datasnap.DBClient, Vcl.Controls, Vcl.Forms,
  FireDAC.Stan.Param, Data.DB, System.Classes;

type
  // Test methods for class TFrmCargos

  TestTFrmCargos = class(TTestCase)
  strict private
    FFrmCargos: TFrmCargos;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestbtnNovoClick;
    procedure TestbtnSalvarClick;
    procedure TestFormCreate;
    procedure TestgridCargosCellClick;
    procedure TestbtnEditarClick;
    procedure TestbtnExcluirClick;
    procedure Testlistar;
  end;

implementation

procedure TestTFrmCargos.SetUp;
begin
  FFrmCargos := TFrmCargos.Create(nil);
end;

procedure TestTFrmCargos.TearDown;
begin
  FFrmCargos.Free;
  FFrmCargos := nil;
end;

procedure TestTFrmCargos.TestbtnNovoClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCargos.btnNovoClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCargos.TestbtnSalvarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCargos.btnSalvarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCargos.TestFormCreate;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCargos.FormCreate(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCargos.TestgridCargosCellClick;
var
  Column: TColumn;
begin
  // TODO: Setup method call parameters
  FFrmCargos.gridCargosCellClick(Column);
  // TODO: Validate method results
end;

procedure TestTFrmCargos.TestbtnEditarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCargos.btnEditarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCargos.TestbtnExcluirClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCargos.btnExcluirClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCargos.Testlistar;
begin
  FFrmCargos.listar;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFrmCargos.Suite);
end.

