unit TestuclCargo;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uPadrao, uclCargo;

type
  // Test methods for class TCargo

  TestTCargo = class(TTestCase)
  strict private
    FCargo: TCargo;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestInserir;
    procedure TestAtualizar;
    procedure TestPesquisar;
    procedure TestPersistir;
    procedure TestExcluir;
  end;

implementation

procedure TestTCargo.SetUp;
begin
  FCargo := TCargo.Create;
end;

procedure TestTCargo.TearDown;
begin
  FCargo.Free;
  FCargo := nil;
end;

procedure TestTCargo.TestInserir;
begin
  FCargo.Inserir;
  // TODO: Validate method results
end;

procedure TestTCargo.TestAtualizar;
begin
  FCargo.Atualizar;
  // TODO: Validate method results
end;

procedure TestTCargo.TestPesquisar;
var
  ReturnValue: Boolean;
  CodCargo: Integer;
begin
  // TODO: Setup method call parameters
  CodCargo := 2;

  ReturnValue := FCargo.Pesquisar(CodCargo);

  // TODO: Validate method results

  CheckFalse(ReturnValue, 'Cargo não encontrado');

end;

procedure TestTCargo.TestPersistir;
var
  Novo: Boolean;
begin
  // TODO: Setup method call parameters
  FCargo.Persistir(Novo);
  // TODO: Validate method results
end;

procedure TestTCargo.TestExcluir;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FCargo.Excluir;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCargo.Suite);
end.

